mopensuse::config::git_server::files:
    git:
        path: '/srv/git/'
        owner: 'root'
        group: 'root'
        mode: '0755'
        ensure: 'directory'
    morawskim:
        path: '/srv/git/morawskim'
        owner: 'marcin'
        group: 'nogroup'
        mode: '0755'
        ensure: 'directory'

mopensuse::config::apache2::modules:
    php5:
        ensure: absent
        name: php5
    proxy:
        name: proxy
    proxy_fcgi:
        name: proxy_fcgi
    proxy_http:
        name: proxy_http
    ssl:
        name: ssl
    rewrite:
        name: rewrite
    userdir:
        name: userdir
    version:
        name: version
    headers:
        name: headers
    filter:
        name: filter
    deflate:
        name: deflate

mopensuse::config::apache2::custom::files:
    mmo:
        path: '/etc/apache2/conf.d/mmo.conf'
        source: 'puppet:///configuration/apache2/mmo.conf'
        owner: 'marcin'
        group: 'root'
        mode: '0644'
    vhost_fpm_template:
        path: '/etc/apache2/vhosts.d/vhost-fpm.template'
        source: 'puppet:///configuration/apache2/vhosts.d/vhost-fpm.template'
        owner: 'root'
        group: 'root'
        mode: '0644'
    vhost_fpm_ssl_template:
        path: '/etc/apache2/vhosts.d/vhost-fpm-ssl.template'
        source: 'puppet:///configuration/apache2/vhosts.d/vhost-fpm-ssl.template'
        owner: 'root'
        group: 'root'
        mode: '0644'
    vhost_default:
        path: '/etc/apache2/vhosts.d/000-default.conf'
        source: 'puppet:///configuration/apache2/vhosts.d/000-default.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
    '/etc/apache2/mod_userdir.conf':
        source: 'puppet:///configuration/apache2/mod_userdir.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
    '/srv/www/vhosts':
        ensure: 'directory'
        mode: '0750'
        owner: 'wwwrun'
        group: 'root'
    userdir:
        ensure: 'directory'
        path: '/srv/www/userdir/'
        owner: 'root'
        group: 'root'
        mode: '0755'
    '/var/log/apache2':
        ensure: 'directory'
        owner: 'root'
        group: 'www'
        mode: '0750'
    '/srv/www/userdir/marcin':
        ensure: 'directory'
        owner: 'marcin'
        group: 'www'
        mode: '0755'
    '/srv/www/vhosts/marcin':
        ensure: 'directory'
        owner: 'marcin'
        group: 'www'
        mode: '2750'

mopensuse::config::nullmailer::files:
    adminaddr:
        path: '/etc/nullmailer/adminaddr'
        source: 'puppet:///configuration/nullmailer/adminaddr'
        owner: 'nullmailer'
        group: 'nullmailer'
        mode: '0640'
    remotes:
        path: '/etc/nullmailer/remotes'
        source: 'puppet:///configuration/nullmailer/remotes'
        owner: 'nullmailer'
        group: 'nullmailer'
        mode: '0640'
    defaultdomain:
        path: '/etc/nullmailer/defaultdomain'
        source: 'puppet:///configuration/nullmailer/defaultdomain'
        owner: 'nullmailer'
        group: 'nullmailer'
        mode: '0644'
    me:
       path: '/etc/nullmailer/me'
       source: 'puppet:///configuration/nullmailer/me'
       owner: 'nullmailer'
       group: 'nullmailer'
       mode: '0644'

mopensuse::config::vagrant::files:
    sudoers:
        path: '/etc/sudoers.d/vagrant'
        source: 'puppet:///configuration/sudo/vagrant'
        owner: 'root'
        group: 'root'
        mode: '0600'

mopensuse::config::osc::files:
    sudoers:
        path: '/etc/sudoers.d/osc'
        source: 'puppet:///configuration/sudo/osc'
        owner: 'root'
        group: 'root'
        mode: '0600'

mopensuse::config::steam::files:
    firewall:
        path: '/etc/sysconfig/SuSEfirewall2.d/services/steam-streaming'
        source: 'puppet:///configuration/SuSEFirewall/steam-streaming'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::sysctl::files:
    inotify:
        path: '/etc/sysctl.d/60-inotify.conf'
        source: 'puppet:///configuration/sysctl/inotify'
        owner: 'root'
        group: 'root'
        mode: '0644'
    iptables:
        path: '/etc/sysctl.d/40-ipforward.conf'
        source: 'puppet:///configuration/sysctl/ipforward'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php::files:
    customini:
        path: '/etc/php7/conf.d/99-custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'
    phpinfo:
        path: '/srv/www/htdocs/phpinfo.php'
        source: 'puppet:///configuration/php/phpinfo.php'
        owner: 'wwwrun'
        group: 'www'
        mode: '0644'

mopensuse::config::dnsmasq::files:
    apparmor:
        path: '/etc/apparmor.d/local/usr.sbin.dnsmasq'
        source: 'puppet:///configuration/apparmor/usr.sbin.dnsmasq'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::nfs_server::exports:
    marcin:
        path: '/srv/nfs/marcin'
        owner: 'marcin'
        group: 'users'
        mode: '0755'
    public:
        path: '/srv/nfs/public'
        owner: 'root'
        group: 'users'
        mode: '1775'

mopensuse::config::cgit::cgit_host: 'cgit.test'
mopensuse::config::cgit::cgit_host_aliases:
        - 'www.cgit.test'
mopensuse::config::cgit::files:
    /var/cache/cgit:
        ensure: 'directory'
        owner: 'wwwrun'
        group: 'root'
        mode: '0700'
    vhost:
        path: '/etc/apache2/vhosts.d/cgit.test.conf'
        source: 'puppet:///configuration/apache2/cgit.test.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
    cgitrc:
        path: '/etc/cgitrc'
        source: 'puppet:///configuration/cgit/cgitrc'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::mysql::files:
    query_log:
        path: '/etc/my.cnf.d/log_query.cnf'
        source: 'puppet:///configuration/mysql/log_query.cnf'
        owner: 'root'
        group: 'mysql'
        mode: '0640'

mopensuse::config::php53v::files:
    customini53v:
        path: '/opt/php/php53v/etc/php5/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php54v::files:
    customini54v:
        path: '/opt/php/php54v/etc/php5/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php55v::files:
    customini55v:
        path: '/opt/php/php55v/etc/php5/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php56v::files:
    customini56v:
        path: '/opt/php/php56v/etc/php5/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php70v::files:
    customini70v:
        path: '/opt/php/php70v/etc/php7/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php71v::files:
    customini71v:
        path: '/opt/php/php71v/etc/php7/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::php72v::files:
    customini72v:
        path: '/opt/php/php72v/etc/php7/conf.d/custom.ini'
        source: 'puppet:///configuration/php/custom.ini'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::phpmyadmin::phpmyadmin_host: 'phpmyadmin.test'
mopensuse::config::phpmyadmin::files:
    /etc/apache2/vhosts.d/phpmyadmin.test.conf:
        source: 'puppet:///configuration/apache2/vhosts.d/phpmyadmin.test.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::phpmyadmin::phpmyadmin_servernode:
    localhost3306:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3306'
        server_group: 'default'
        user: ''
        myserver_port: 3306
    localhost3307:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3307'
        server_group: 'default'
        user: ''
        myserver_port: 3307
    localhost3308:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3308'
        server_group: 'default'
        user: ''
        myserver_port: 3308

mopensuse::config::phpmyadmin40::phpmyadmin_host: 'phpmyadmin40.test'
mopensuse::config::phpmyadmin40::files:
    phpmyadminvhost40:
        path: '/etc/apache2/vhosts.d/phpmyadmin40.test.conf'
        source: 'puppet:///configuration/apache2/vhosts.d/phpmyadmin40.test.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::phpmyadmin40::phpmyadmin_servernode:
    phpmyadmin40localhost3306:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3306'
        server_group: 'default'
        user: ''
        myserver_port: 3306
    phpmyadmin40localhost3307:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3307'
        server_group: 'default'
        user: ''
        myserver_port: 3307
    phpmyadmin40localhost3308:
        myserver_name: '127.0.0.1'
        verbose_name: 'localhost 3308'
        server_group: 'default'
        user: ''
        myserver_port: 3308

mopensuse::config::network_manager::files:
    '/etc/NetworkManager/conf.d/vbox.conf':
        source: 'puppet:///configuration/NetworkManager/vbox.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::pam::files:
    '/etc/security/limits.d/mmo.conf':
        source: 'puppet:///configuration/pam/pam_limits.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

mopensuse::config::docker::files:
    '/etc/docker/':
        ensure: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0700'
    '/etc/docker/certs.d/':
        ensure: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
    '/etc/docker/certs.d/nexus.office.local':
        ensure: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
    '/etc/docker/certs.d/nexus.office.local/ca.crt':
        source: 'puppet:///configuration/certs/psat.crt'
        owner: 'root'
        group: 'root'
        mode: '0644'
