node default {
  include mopensuse::zypper::repositories::benchmark
  include mopensuse::zypper::repositories::devel_languages_go
  include mopensuse::zypper::repositories::devel_languages_python
  include mopensuse::zypper::repositories::devel_languages_ruby_extensions
  include mopensuse::zypper::repositories::devel_languages_rust
  include mopensuse::zypper::repositories::devel_libraries_c_cpp
  include mopensuse::zypper::repositories::devel_tools_building
  include mopensuse::zypper::repositories::devel_tools
  include mopensuse::zypper::repositories::education
  include mopensuse::zypper::repositories::filesystems
  include mopensuse::zypper::repositories::games_tools
  include mopensuse::zypper::repositories::google_chrome
  include mopensuse::zypper::repositories::hardware
  include mopensuse::zypper::repositories::isv_owncloud_desktop
  include mopensuse::zypper::repositories::jenkins
  include mopensuse::zypper::repositories::kde_extra
  include mopensuse::zypper::repositories::kde_frameworks5
  include mopensuse::zypper::repositories::kde_kup
  include mopensuse::zypper::repositories::libdvdcss
  include mopensuse::zypper::repositories::morawskim
  include mopensuse::zypper::repositories::multimedia_apps
  include mopensuse::zypper::repositories::network
  include mopensuse::zypper::repositories::network_utilities
  include mopensuse::zypper::repositories::packman
  include mopensuse::zypper::repositories::repo_debug_non_oss
  include mopensuse::zypper::repositories::repo_debug
  include mopensuse::zypper::repositories::repo_debug_update_non_oss
  include mopensuse::zypper::repositories::repo_debug_update
  include mopensuse::zypper::repositories::security
  include mopensuse::zypper::repositories::security_privacy
  include mopensuse::zypper::repositories::security_tools
  include mopensuse::zypper::repositories::server_database
  include mopensuse::zypper::repositories::server_mail
  include mopensuse::zypper::repositories::server_monitoring
  include mopensuse::zypper::repositories::server_php_extensions
  include mopensuse::zypper::repositories::skype_stable
  include mopensuse::zypper::repositories::slack
  include mopensuse::zypper::repositories::systemsmanagement_machinery
  include mopensuse::zypper::repositories::utilities
  include mopensuse::zypper::repositories::virtualization_containers
  include mopensuse::zypper::repositories::vivaldi
  include mopensuse::zypper::repositories::x11_utilities
  include mopensuse::zypper::repositories::yarn
}
