node default {
  include mopensuse::packages::ag
  include mopensuse::packages::apache2
  include mopensuse::packages::apachetop
  include mopensuse::packages::augeas
  include mopensuse::packages::bash
  include mopensuse::packages::bsdtar
  include mopensuse::packages::bundler
  include mopensuse::packages::ca_certificates
  include mopensuse::packages::colordiff
  include mopensuse::packages::colout
  include mopensuse::packages::composer
  include mopensuse::packages::ctags
  include mopensuse::packages::dateutils
  include mopensuse::packages::devel_java
  include mopensuse::packages::dhcpd
  include mopensuse::packages::dnsmasq
  include mopensuse::packages::enhancd
  include mopensuse::packages::exa
  include mopensuse::packages::filesystem
  include mopensuse::packages::firewall
  include mopensuse::packages::fontawesome
  include mopensuse::packages::foreman
  include mopensuse::packages::fzf_tmux
  include mopensuse::packages::fzf
  include mopensuse::packages::git_extras
  include mopensuse::packages::git_hooks
  include mopensuse::packages::httpry
  include mopensuse::packages::jq
  include mopensuse::packages::json_tools
  include mopensuse::packages::libguestfs
  include mopensuse::packages::mailutil
  include mopensuse::packages::mc
  include mopensuse::packages::monoid
  include mopensuse::packages::msmtp
  include mopensuse::packages::mutt
  include mopensuse::packages::netcat_openbsd
  include mopensuse::packages::netsed
  include mopensuse::packages::network
  include mopensuse::packages::nfs
  include mopensuse::packages::nfs_server
  include mopensuse::packages::ngrep
  include mopensuse::packages::ngrok
  include mopensuse::packages::nodejs
  include mopensuse::packages::o_saft
  include mopensuse::packages::offlineimap
  include mopensuse::packages::openssl
  include mopensuse::packages::openvpn
  include mopensuse::packages::password_store
  include mopensuse::packages::patchutils
  include mopensuse::packages::php_docs
  include mopensuse::packages::php
  include mopensuse::packages::puppet
  include mopensuse::packages::pv
  include mopensuse::packages::pwgen
  include mopensuse::packages::python3_pipsi
  include mopensuse::packages::python_pipsi
  include mopensuse::packages::quilt
  include mopensuse::packages::rar
  include mopensuse::packages::redis
  include mopensuse::packages::sshd
  include mopensuse::packages::sshfs
  include mopensuse::packages::strace
  include mopensuse::packages::systemd
  include mopensuse::packages::tcpdump
  include mopensuse::packages::tmux
  include mopensuse::packages::tree
  include mopensuse::packages::vagrant
  include mopensuse::packages::vcs
  include mopensuse::packages::vim
  include mopensuse::packages::virtualbox
  include mopensuse::packages::wget
  include mopensuse::packages::xdebug_tmpfiles
  include mopensuse::packages::yadm
  include mopensuse::packages::yarn
  include mopensuse::packages::gui::adobe_source_code_pro_fonts
  include mopensuse::packages::gui::chrome
  include mopensuse::packages::gui::chromium
  include mopensuse::packages::gui::gitg
  include mopensuse::packages::gui::gvim
  include mopensuse::packages::gui::jetbrains_toolbox
  include mopensuse::packages::gui::kate
  include mopensuse::packages::gui::kcachegrind
  include mopensuse::packages::gui::kdeconnect
  include mopensuse::packages::gui::kdiff3
  include mopensuse::packages::gui::krusader
  include mopensuse::packages::gui::mozillathunderbird
  include mopensuse::packages::gui::owasp_zap
  include mopensuse::packages::gui::pgadmin
  include mopensuse::packages::gui::plasma_nm_openvpn
  include mopensuse::packages::gui::poedit
  include mopensuse::packages::gui::recordmydesktop
  include mopensuse::packages::gui::redshift
  include mopensuse::packages::gui::retext
  include mopensuse::packages::gui::sddm
  include mopensuse::packages::gui::skypeforlinux
  include mopensuse::packages::gui::soapui
  include mopensuse::packages::gui::telegram
  include mopensuse::packages::gui::vcs
  include mopensuse::packages::gui::virtualbox_qt
  include mopensuse::packages::gui::vivaldi
  include mopensuse::packages::gui::xbindkeys
  include mopensuse::packages::gui::xclip
  include mopensuse::packages::gui::xrectsel
  include mopensuse::packages::gui::xsel
  include mopensuse::packages::gui::yakuake
  include mopensuse::packages::gui::zeal
  include mopensuse::packages::gui::zenity
  
  include mopensuse::user::marcin
}
